"use client";

export const TOS_CONTENT = `🧾 CULBRIDGE TERMS OF SERVICE (LEGAL VERSION)
Last Updated: 22/Apr/2026

1. AGREEMENT TO TERMS
1.1 Binding Agreement
These Terms of Service (“Terms”) constitute a legally binding agreement between:
Culbridge (“Company”, “we”, “us”, “our”)
User / Exporter (“you”, “your”)
By accessing or using the Culbridge platform, you agree to be bound by these Terms.
If you do not agree, you must not use the platform.

2. DESCRIPTION OF SERVICE
2.1 Platform Overview
Culbridge is a digital workflow and data structuring platform designed to assist exporters in preparing shipment-related documentation and organizing compliance-related information.
The platform provides:
structured shipment data entry tools
export documentation management features
rule-based informational outputs generated by backend systems
data organization for export readiness assessment
2.2 No Regulatory Authority
Culbridge is not:
a government agency
a customs authority
a certification body
a legal or regulatory compliance authority

3. DEFINITIONS
3.1 “Platform”
The Culbridge software system, including web interfaces, APIs, and related services.
3.2 “Services”
All features provided through the Platform, including shipment structuring and informational compliance outputs.
3.3 “User Data”
Any data submitted by users, including but not limited to shipment information, product details, documents, and test results.
3.4 “Compliance Output”
Any system-generated output relating to shipment readiness or regulatory alignment, including:
pass/warning/block indicators
rule failure reports
missing documentation flags
Compliance Outputs are informational only and do not constitute certification or legal approval.

4. NATURE OF THE SERVICE
4.1 Informational and Structural Tool
Culbridge provides tools for structuring and organizing export-related data.
All outputs are generated for informational purposes only and are based on system-defined rules and user-provided data.
4.2 No Guarantee of Regulatory Outcome
Culbridge does not guarantee:
customs clearance
regulatory approval in any jurisdiction
acceptance of shipments by any authority
4.3 No Legal or Professional Advice
Culbridge does not provide legal, regulatory, or customs brokerage advice.
Users are solely responsible for obtaining independent professional advice where required.

5. USER RESPONSIBILITIES
5.1 Accuracy and Completeness
You are solely responsible for ensuring that all information provided to the Platform is:
accurate
complete
truthful
properly classified (including HS codes and product descriptions)
5.2 Regulatory Compliance
You are solely responsible for ensuring that your shipments comply with all applicable:
import/export laws
customs regulations
safety standards
destination country requirements
5.3 Reliance on Outputs
You acknowledge and agree that:
Any reliance on Compliance Outputs or any information provided by the Platform is strictly at your own risk.

6. LIMITATION OF LIABILITY
6.1 General Limitation
To the maximum extent permitted by law, Culbridge shall not be liable for any loss or damage arising from or related to:
shipment rejection or seizure
customs delays or refusal
financial losses or business interruption
inaccurate or incomplete user data
reliance on Platform outputs
actions of third parties (including customs authorities, logistics providers, or regulators)
6.2 Exclusion of Indirect Damages
Culbridge shall not be liable for any indirect, incidental, consequential, or punitive damages, including but not limited to:
loss of revenue or profit
loss of business opportunity
reputational harm
supply chain disruption
6.3 Liability Cap
To the maximum extent permitted by law, Culbridge's total aggregate liability shall not exceed:
the total amount paid by you for use of the Platform in the twelve (12) months preceding the event giving rise to the claim
(or a nominal statutory amount where no fees have been paid).

7. COMPLIANCE OUTPUT DISCLAIMER
7.1 Informational Nature
All Compliance Outputs are:
automated system-generated assessments
based on user input and predefined logic
They do not constitute:
legal certification
regulatory approval
official inspection results
7.2 No Legal Effect
Compliance Outputs have no legal effect and do not replace any governmental or regulatory process.

8. DATA AND INTELLECTUAL PROPERTY
8.1 User Data Ownership
Users retain ownership of their submitted data.
8.2 Platform Rights
Culbridge is granted a limited license to:
process User Data to provide Services
store and transmit User Data
generate system outputs
Culbridge may use anonymized and aggregated data for system improvement, analytics, and performance optimization.

9. SERVICE AVAILABILITY
Culbridge does not guarantee:
uninterrupted access to the Platform
error-free operation
accuracy of all system computations
continuous availability of third-party integrations

10. THIRD-PARTY SERVICES
The Platform may depend on third-party services, including but not limited to:
cloud hosting providers
external APIs
regulatory data sources
Culbridge is not responsible for failures, inaccuracies, or interruptions caused by third-party systems.

11. TERMINATION
Culbridge reserves the right to suspend or terminate access to the Platform at its sole discretion, including in cases of:
suspected fraud or misuse
security risks
violation of these Terms
illegal activity

12. GOVERNING LAW
These Terms shall be governed by and interpreted in accordance with the laws of:
[Insert Jurisdiction — Nigeria / United Kingdom / EU entity location]

13. FINAL INTERPRETATION PRINCIPLE
13.1 Core Legal Understanding
The parties acknowledge that:
Culbridge is a data structuring and compliance-preparation platform.
Users remain solely responsible for all regulatory and shipment outcomes.`;

export const DPA_CONTENT = `🧾 CULBRIDGE DATA PROCESSING AGREEMENT (DPA)
Last Updated: October 22, 2026

1. PARTIES TO THIS AGREEMENT
This Data Processing Agreement (“DPA”) is entered into between:
Culbridge (“Processor”, “we”, “us”, “our”)
Client / Exporter Organization (“Controller”, “you”, “your”)
Together referred to as “the Parties”.

2. PURPOSE OF THIS AGREEMENT
2.1 Scope
This DPA governs the processing of personal and business data by Culbridge on behalf of the Controller in connection with the use of the Culbridge platform.
2.2 Relationship to Main Agreement
This DPA forms part of the overall service agreement between the Parties and applies where:
personal data is processed
shipment and exporter data includes identifiable individuals
EU/UK GDPR or equivalent regulations apply

3. ROLES OF THE PARTIES (CRITICAL LEGAL CLASSIFICATION)
3.1 Data Controller (Client)
The Client acts as Data Controller and determines:
what data is collected
why data is collected
how data is initially submitted to Culbridge
legal basis for processing personal data
3.2 Data Processor (Culbridge)
Culbridge acts as Data Processor and processes data strictly on behalf of the Controller for the purpose of providing the Platform services.
3.3 No Independent Control
Culbridge does not:
determine legal purpose of data collection
decide what data is required from end users
use data outside instructions provided by the Controller

4. NATURE OF DATA PROCESSING
4.1 Processing Activities
Culbridge processes data for the following purposes:
structured shipment data processing
export documentation organization
compliance-related rule execution (system-generated)
storage and retrieval of shipment records
audit and traceability support
4.2 Types of Data Processed
This may include:
names and contact details of exporters and suppliers
business identifiers
shipment and product data
HS codes and classification data
laboratory and certification documents
metadata related to compliance workflows
4.3 Categories of Data Subjects
Data may relate to:
exporters
suppliers
logistics operators
business representatives

5. PROCESSING INSTRUCTIONS
5.1 Controller Instructions
Culbridge shall process personal data only:
in accordance with documented instructions from the Controller
as required to provide Platform functionality
as required by applicable law
5.2 Outside Instructions
If Culbridge is required by law to process data outside Controller instructions, we will notify the Controller unless legally prohibited.

6. CONFIDENTIALITY
6.1 Confidential Handling
Culbridge ensures that all personnel authorized to process personal data are bound by confidentiality obligations.
6.2 Access Control
Access to personal data is restricted to personnel who require it for service operation.

7. SECURITY MEASURES
7.1 Technical Safeguards
Culbridge implements appropriate technical and organizational measures, including:
encryption of data in transit
secure authentication mechanisms
role-based access controls
system monitoring and logging
secure cloud infrastructure
7.2 Security Limitations
No system is completely secure. Culbridge does not guarantee absolute protection against unauthorized access or breaches.

8. SUB-PROCESSORS
8.1 Authorization
The Controller authorizes Culbridge to engage sub-processors necessary for service delivery, including:
cloud infrastructure providers
database hosting services
API and integration services
8.2 Sub-Processor Obligations
Culbridge shall ensure that all sub-processors are bound by data protection obligations no less protective than those set out in this DPA.
8.3 Liability for Sub-Processors
Culbridge remains responsible for the performance of its sub-processors.

9. INTERNATIONAL DATA TRANSFERS
9.1 Transfer Conditions
Data may be transferred and processed outside the Controller's jurisdiction where necessary for service operation.
9.2 Safeguards
Culbridge ensures appropriate safeguards for international transfers, which may include:
standard contractual clauses (SCCs)
adequate data protection frameworks
equivalent legal mechanisms

10. DATA SUBJECT RIGHTS
10.1 Support for Requests
Culbridge will assist the Controller in responding to data subject requests, including:
access requests
correction requests
deletion requests
restriction of processing
10.2 Execution Responsibility
The Controller remains responsible for responding to data subject requests.

11. DATA BREACH NOTIFICATION
11.1 Notification Obligation
Culbridge shall notify the Controller without undue delay upon becoming aware of a personal data breach affecting processed data.
11.2 Information Provided
Where possible, notification shall include:
nature of the breach
categories of data affected
likely consequences
measures taken or proposed

12. DATA RETENTION AND DELETION
12.1 Retention
Culbridge shall retain personal data only for the duration necessary to provide the Services or as required by law.
12.2 Deletion or Return
Upon termination of services, Culbridge shall:
delete personal data, or
return data to the Controller, where technically feasible
unless retention is required by law.

13. AUDIT AND COMPLIANCE
13.1 Audit Rights
The Controller may request reasonable information to verify compliance with this DPA.
13.2 Limitations
Audits must not:
disrupt normal operations
compromise security systems
violate confidentiality obligations

14. LIABILITY
14.1 Processor Liability
Culbridge is liable only for damages caused by:
failure to comply with this DPA
processing outside documented instructions
breach of GDPR obligations applicable to processors
14.2 Controller Liability
The Controller remains responsible for:
legality of data collection
accuracy of instructions
lawful basis for processing
14.3 Exclusion of Indirect Damages
Culbridge is not liable for:
loss of revenue
regulatory penalties caused by Controller misuse
indirect or consequential damages

15. TERMINATION
This DPA terminates automatically upon termination of the main service agreement unless data retention obligations apply.

16. FINAL INTERPRETATION PRINCIPLE
16.1 Core Legal Model
The Parties acknowledge:
Culbridge acts strictly as a data processor executing structured export workflow operations on behalf of the Controller. The Controller retains full legal responsibility for the purpose, legality, and accuracy of data collection and regulatory compliance decisions.

🧠 CRITICAL FOUNDER INSIGHT (NOT LEGAL CLAUSE)
This document is what enables you to scale into:
EU exporters
enterprise logistics clients
regulated supply chain systems
Without it, you are legally treated as a data controller by default, which increases liability significantly.`;

export const LIABILITY_CONTENT = `🧾 LIABILITY LIMITATION CLAUSE (CULBRIDGE)
1. PURPOSE OF THIS CLAUSE
This Liability Limitation Clause defines the extent to which Culbridge (“Company”, “we”, “us”, “our”) is legally responsible for losses arising from use of the Platform.
This clause applies to all users of Culbridge, including exporters, organizations, and enterprise clients.
2. CORE DISCLAIMER OF REGULATORY OUTCOMES
2.1 No Guarantee of Regulatory Approval
Culbridge does not guarantee, warrant, or represent that any shipment, export, or documentation prepared or structured using the Platform will:
be accepted by customs authorities
comply with regulatory requirements in any jurisdiction
pass inspection or border clearance processes
receive approval from governmental or trade bodies
2.2 Independent Regulatory Responsibility
All regulatory, customs, and compliance outcomes remain the sole responsibility of the User.
Users acknowledge that:
Regulatory approval decisions are made exclusively by third-party authorities outside the control of Culbridge.
3. EXCLUSION OF LIABILITY FOR SHIPMENT OUTCOMES
3.1 Shipment Rejection
Culbridge shall not be liable for any loss, damage, or consequence arising from:
shipment rejection at any border or port
detention or seizure of goods
delays in customs clearance
refusal of import or export authorization
3.2 Financial Losses
Culbridge shall not be liable for any financial losses arising from, including but not limited to:
rejected shipments
delayed deliveries
contract penalties
lost business opportunities
spoilage or degradation of goods due to delays
3.3 Third-Party Actions
Culbridge is not responsible for actions, decisions, or omissions of:
customs authorities
regulatory agencies
logistics providers
inspection bodies
shipping carriers
4. LIMITATION OF LIABILITY
4.1 General Limitation
To the maximum extent permitted by applicable law, Culbridge shall not be liable for any:
indirect damages
incidental damages
consequential damages
punitive damages
special damages
arising from or related to the use of the Platform.
4.2 Excluded Loss Categories
Without limitation, Culbridge is not liable for:
loss of revenue or profit
loss of business contracts
reputational damage
operational disruption
supply chain failure
regulatory penalties imposed on the User
5. MAXIMUM LIABILITY CAP
5.1 Liability Ceiling
In all cases, Culbridge's total aggregate liability arising from any claim shall not exceed:
the total fees paid by the User to Culbridge in the twelve (12) months preceding the event giving rise to the claim
(or a nominal statutory amount where no fees have been paid).
6. NO RELIANCE WARRANTY
6.1 User Acknowledgement
Users acknowledge and agree that:
Platform outputs are informational and system-generated
compliance assessments are not legally binding
no representation is made regarding regulatory acceptance
6.2 Reliance Risk
Any reliance on information, outputs, or recommendations provided by the Platform is strictly at the User's own risk.
7. TECHNICAL LIMITATION ACKNOWLEDGEMENT
Users acknowledge that:
system outputs depend on user-provided data accuracy
backend rule execution is automated and may not reflect real-time regulatory changes
data processing systems may contain delays, errors, or limitations
8. FORCE MAJEURE AND EXTERNAL EVENTS
Culbridge shall not be liable for failure or delay caused by events beyond its reasonable control, including:
government actions or regulatory changes
customs enforcement decisions
infrastructure failures
internet or cloud service outages
geopolitical or trade disruptions
9. FINAL LEGAL INTERPRETATION PRINCIPLE
9.1 Core Liability Structure
The Parties agree that:
Culbridge provides structured export workflow and compliance-preparation tools only.
Final regulatory outcomes are independent decisions made by external authorities.
The User assumes full responsibility for shipment legality and acceptance.

🧠 CRITICAL FOUNDER INSIGHT (NON-LEGAL EXPLANATION)
This clause is doing one critical thing:
It legally separates:
your system (data + structure tool)
from
government decisions (customs + regulation outcomes)
Without this clause, your platform can be interpreted as:
"advising or guaranteeing compliance outcomes"
which is where liability exposure becomes real.
`;
export const PRIVACY_CONTENT = `🧾 CULBRIDGE PRIVACY POLICY (LEGAL VERSION)
Last Updated: October 22, 2026.


1. AGREEMENT TO POLICY
1.1 Binding Nature
This Privacy Policy describes how Culbridge (“Company”, “we”, “us”, “our”) collects, uses, stores, and protects personal and business data when you access or use the Platform.
By using the Platform, you agree to the practices described in this Policy.
If you do not agree, you must discontinue use of the Platform.

2. SCOPE OF THIS POLICY
2.1 Applicability
This Policy applies to:
web application users
API consumers
registered exporters
any entity submitting data to Culbridge systems
2.2 Covered Data
This Policy covers all data processed through the Platform, including:
account information
shipment data
product information
compliance-related inputs
uploaded documents
system interaction logs

3. DATA WE COLLECT
3.1 Information You Provide Directly
We collect information that you voluntarily submit, including:
full name and contact details
email address and login credentials
business or company information
shipment details (commodity, origin, destination, HS codes)
product descriptions and export data
lab test results and compliance documents
3.2 Automatically Collected Data
We may automatically collect:
IP address
device type and browser information
session activity logs
platform usage analytics
error and performance data
3.3 Third-Party Data (If Applicable)
We may receive limited data from third-party services used for:
authentication
payment processing
compliance verification APIs
infrastructure and hosting services

4. PURPOSE OF DATA USE
4.1 Core Operational Use
We use collected data to:
provide platform functionality
process shipment submissions
generate compliance-related outputs
maintain user accounts
improve system performance and reliability
4.2 System Processing (Critical Clause)
User data is processed by automated systems to:
structure shipment information
evaluate rule-based compliance conditions
generate informational outputs
4.3 No Human Compliance Decisioning
Culbridge does not manually assess or approve shipments unless explicitly stated.
All compliance outputs are system-generated.

5. DATA STORAGE AND SECURITY
5.1 Storage Location
Data may be stored in secure cloud infrastructure providers located in multiple jurisdictions.
5.2 Security Measures
We implement reasonable technical and organizational safeguards, including:
encryption in transit
access control restrictions
authentication mechanisms
monitoring and logging systems
5.3 Security Limitation
No system is completely secure.
We do not guarantee absolute protection against unauthorized access, breach, or data loss.

6. DATA SHARING AND DISCLOSURE
6.1 No Sale of Personal Data
Culbridge does not sell personal data.
6.2 Permitted Disclosures
We may share data only in the following cases:
with service providers supporting platform operations
when required by law or regulatory authorities
to prevent fraud, abuse, or security threats
in connection with business restructuring or acquisition
6.3 Aggregated Data
We may use anonymized and aggregated data for:
system improvement
analytics
performance optimization
research and development

7. USER RIGHTS
7.1 Access and Control
Users may request:
access to their stored data
correction of inaccurate data
deletion of account data (subject to legal retention requirements)
7.2 Limitation of Rights
Certain data may be retained where required for:
legal compliance
fraud prevention
system integrity
audit and security purposes

8. DATA RETENTION
8.1 Retention Period
We retain data only as long as necessary for:
provision of services
legal compliance obligations
dispute resolution
system integrity and audit purposes
8.2 Deletion
When no longer required, data is securely deleted or anonymized.

9. COOKIES AND TRACKING
9.1 Use of Cookies
We may use cookies and similar technologies to:
maintain user sessions
improve platform performance
analyze usage behavior
9.2 User Control
Users may disable cookies in browser settings, but this may affect platform functionality.

10. INTERNATIONAL DATA TRANSFERS
User data may be processed in countries other than the user's jurisdiction.
By using the Platform, you consent to such transfers where necessary for service operation.

11. CHILDREN'S DATA
The Platform is not intended for use by individuals under the age of 18.
We do not knowingly collect data from minors.

12. THIRD-PARTY SERVICES
The Platform may rely on third-party infrastructure and services.
Culbridge is not responsible for the privacy practices or failures of third-party providers.

13. LIMITATION OF LIABILITY
To the maximum extent permitted by law:
Culbridge shall not be liable for:
unauthorized access to user data
data loss or corruption
third-party breaches
user misuse of platform features
indirect or consequential damages arising from data usage

14. DATA PROCESSING PRINCIPLE
14.1 Core Understanding
Users acknowledge that:
Culbridge is a structured data processing system for export workflows, not a regulatory authority or legal custodian of compliance decisions.

15. CHANGES TO THIS POLICY
We reserve the right to update this Privacy Policy at any time.
Continued use of the Platform constitutes acceptance of any revised version.

16. CONTACT INFORMATION
For privacy-related inquiries:
Email: helloculbridgetrade@gmail.com
Platform: https://culbridge.cloud

🧠 FINAL STRUCTURAL PRINCIPLE
This Policy is based on a single operational rule:
Culbridge processes user-submitted export data strictly for workflow structuring and informational output generation. Users remain responsible for all regulatory and compliance outcomes.`;




