"use client";

export const TOS_CONTENT = `🧾 CULBRIDGE TERMS OF SERVICE (LEGAL VERSION)
Last Updated: 22/Apr/2026

1. AGREEMENT TO TERMS
1.1 Binding Agreement
These Terms of Service (“Terms”) constitute a legally binding agreement between:
Culbridge (“Company”, “we”, “us”, “our”)
User / Exporter (“you”, “your”)
By accessing or using the Culbridge platform, you agree to be bound by these Terms.
If you do not agree, you must not use the platform.

2. DESCRIPTION OF SERVICE
2.1 Platform Overview
Culbridge is a digital workflow and data structuring platform designed to assist exporters in preparing shipment-related documentation and organizing compliance-related information.
The platform provides:
structured shipment data entry tools
export documentation management features
rule-based informational outputs generated by backend systems
data organization for export readiness assessment
2.2 No Regulatory Authority
Culbridge is not:
a government agency
a customs authority
a certification body
a legal or regulatory compliance authority

3. DEFINITIONS
3.1 “Platform”
The Culbridge software system, including web interfaces, APIs, and related services.
3.2 “Services”
All features provided through the Platform, including shipment structuring and informational compliance outputs.
3.3 “User Data”
Any data submitted by users, including but not limited to shipment information, product details, documents, and test results.
3.4 “Compliance Output”
Any system-generated output relating to shipment readiness or regulatory alignment, including:
pass/warning/block indicators
rule failure reports
missing documentation flags
Compliance Outputs are informational only and do not constitute certification or legal approval.

4. NATURE OF THE SERVICE
4.1 Informational and Structural Tool
Culbridge provides tools for structuring and organizing export-related data.
All outputs are generated for informational purposes only and are based on system-defined rules and user-provided data.
4.2 No Guarantee of Regulatory Outcome
Culbridge does not guarantee:
customs clearance
regulatory approval in any jurisdiction
acceptance of shipments by any authority
4.3 No Legal or Professional Advice
Culbridge does not provide legal, regulatory, or customs brokerage advice.
Users are solely responsible for obtaining independent professional advice where required.

5. USER RESPONSIBILITIES
5.1 Accuracy and Completeness
You are solely responsible for ensuring that all information provided to the Platform is:
accurate
complete
truthful
properly classified (including HS codes and product descriptions)
5.2 Regulatory Compliance
You are solely responsible for ensuring that your shipments comply with all applicable:
import/export laws
customs regulations
safety standards
destination country requirements
5.3 Reliance on Outputs
You acknowledge and agree that:
Any reliance on Compliance Outputs or any information provided by the Platform is strictly at your own risk.

6. LIMITATION OF LIABILITY
6.1 General Limitation
To the maximum extent permitted by law, Culbridge shall not be liable for any loss or damage arising from or related to:
shipment rejection or seizure
customs delays or refusal
financial losses or business interruption
inaccurate or incomplete user data
reliance on Platform outputs
actions of third parties (including customs authorities, logistics providers, or regulators)
6.2 Exclusion of Indirect Damages
Culbridge shall not be liable for any indirect, incidental, consequential, or punitive damages, including but not limited to:
loss of revenue or profit
loss of business opportunity
reputational harm
supply chain disruption
6.3 Liability Cap
To the maximum extent permitted by law, Culbridge's total aggregate liability shall not exceed:
the total amount paid by you for use of the Platform in the twelve (12) months preceding the event giving rise to the claim
(or a nominal statutory amount where no fees have been paid).

7. COMPLIANCE OUTPUT DISCLAIMER
7.1 Informational Nature
All Compliance Outputs are:
automated system-generated assessments
based on user input and predefined logic
They do not constitute:
legal certification
regulatory approval
official inspection results
7.2 No Legal Effect
Compliance Outputs have no legal effect and do not replace any governmental or regulatory process.

8. DATA AND INTELLECTUAL PROPERTY
8.1 User Data Ownership
Users retain ownership of their submitted data.
8.2 Platform Rights
Culbridge is granted a limited license to:
process User Data to provide Services
store and transmit User Data
generate system outputs
Culbridge may use anonymized and aggregated data for system improvement, analytics, and performance optimization.

9. SERVICE AVAILABILITY
Culbridge does not guarantee:
uninterrupted access to the Platform
error-free operation
accuracy of all system computations
continuous availability of third-party integrations

10. THIRD-PARTY SERVICES
The Platform may depend on third-party services, including but not limited to:
cloud hosting providers
external APIs
regulatory data sources
Culbridge is not responsible for failures, inaccuracies, or interruptions caused by third-party systems.

11. TERMINATION
Culbridge reserves the right to suspend or terminate access to the Platform at its sole discretion, including in cases of:
suspected fraud or misuse
security risks
violation of these Terms
illegal activity

12. GOVERNING LAW
These Terms shall be governed by and interpreted in accordance with the laws of:
[Insert Jurisdiction — Nigeria / United Kingdom / EU entity location]

13. FINAL INTERPRETATION PRINCIPLE
13.1 Core Legal Understanding
The parties acknowledge that:
Culbridge is a data structuring and compliance-preparation platform.
Users remain solely responsible for all regulatory and shipment outcomes.`;
